apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-test-app-22
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/mvaldron-rhdh/rhtap-go-app-2:9172a77a891b28a025962dd2d6e9e4b6125b5f49@sha256:388ae04a37089b4c55d0ddc4ca52f02bf4db19743348f27ca9583db453beabf7
          name: container-image
