apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chatbot-test-app-22 
  janus-idp.io/tekton: chatbot-test-app-22
  backstage.io/kubernetes-id: chatbot-test-app-22
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chatbot-test-app-22
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml