apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: chatbot-test-app-22
  janus-idp.io/tekton: chatbot-test-app-22
  backstage.io/kubernetes-id: chatbot-test-app-22
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chatbot-test-app-22
resources:
- deployment.yaml
- route.yaml
- service.yaml
